const { sql, getPool } = require('../shared/database');

function toSafeString(value, maxLen = 500) {
    if (value == null) return null;
    const str = String(value).trim();
    return str ? str.slice(0, maxLen) : null;
}

async function ensureTable(pool) {
    // Header table (legacy)
    await pool.request().query(`
        IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PurchaseOrders' AND xtype='U')
        BEGIN
            CREATE TABLE PurchaseOrders (
                Id INT IDENTITY(1,1) PRIMARY KEY,
                ClientId NVARCHAR(100) NOT NULL,
                InstrumentId INT NULL,
                Quantity INT NULL,
                VendorId NVARCHAR(50) NULL,
                VendorName NVARCHAR(255) NULL,
                PoNumber NVARCHAR(100) NULL,
                UnitCost DECIMAL(18,4) NULL,
                TotalCost DECIMAL(18,4) NULL,
                OrderDate DATE NULL,
                Notes NVARCHAR(MAX) NULL,
                DocumentId NVARCHAR(255) NULL,
                CreatedBy NVARCHAR(255) NULL,
                CreatedAt DATETIME2 NULL,
                ModifiedDate DATETIME2 DEFAULT GETUTCDATE(),
                CONSTRAINT UQ_PurchaseOrders_ClientId UNIQUE (ClientId)
            )
        END
    `);

    // Idempotent ALTERs for the supplies-era columns
    await pool.request().query(`
        IF COL_LENGTH('PurchaseOrders', 'SupplyType') IS NULL ALTER TABLE PurchaseOrders ADD SupplyType NVARCHAR(20) NULL;
        IF COL_LENGTH('PurchaseOrders', 'SupplyId') IS NULL ALTER TABLE PurchaseOrders ADD SupplyId INT NULL;
        IF COL_LENGTH('PurchaseOrders', 'OrderNumber') IS NULL ALTER TABLE PurchaseOrders ADD OrderNumber NVARCHAR(100) NULL;
        IF COL_LENGTH('PurchaseOrders', 'ExpectedDate') IS NULL ALTER TABLE PurchaseOrders ADD ExpectedDate DATE NULL;
        IF COL_LENGTH('PurchaseOrders', 'Status') IS NULL ALTER TABLE PurchaseOrders ADD Status NVARCHAR(30) NULL;
        IF COL_LENGTH('PurchaseOrders', 'Subtotal') IS NULL ALTER TABLE PurchaseOrders ADD Subtotal DECIMAL(18,4) NULL;
        IF COL_LENGTH('PurchaseOrders', 'Tax') IS NULL ALTER TABLE PurchaseOrders ADD Tax DECIMAL(18,4) NULL;
        IF COL_LENGTH('PurchaseOrders', 'Shipping') IS NULL ALTER TABLE PurchaseOrders ADD Shipping DECIMAL(18,4) NULL;
        IF COL_LENGTH('PurchaseOrders', 'Total') IS NULL ALTER TABLE PurchaseOrders ADD Total DECIMAL(18,4) NULL;
        IF COL_LENGTH('PurchaseOrders', 'IsAutoGenerated') IS NULL ALTER TABLE PurchaseOrders ADD IsAutoGenerated BIT NULL;
        IF COL_LENGTH('PurchaseOrders', 'ReceivedDate') IS NULL ALTER TABLE PurchaseOrders ADD ReceivedDate DATETIME2 NULL;
    `);

    // Items table for multi-line supply POs
    await pool.request().query(`
        IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PurchaseOrderItems' AND xtype='U')
        BEGIN
            CREATE TABLE PurchaseOrderItems (
                Id INT IDENTITY(1,1) PRIMARY KEY,
                PurchaseOrderId INT NOT NULL,
                SupplyType NVARCHAR(20) NULL,
                SupplyId INT NULL,
                SupplyName NVARCHAR(255) NULL,
                Quantity INT NULL,
                UnitCost DECIMAL(18,4) NULL,
                LineTotal DECIMAL(18,4) NULL,
                CreatedAt DATETIME2 DEFAULT GETUTCDATE()
            )
        END
    `);
    await pool.request().query(`
        IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_PurchaseOrderItems_PurchaseOrderId' AND object_id=OBJECT_ID('PurchaseOrderItems'))
            CREATE INDEX IX_PurchaseOrderItems_PurchaseOrderId ON PurchaseOrderItems(PurchaseOrderId);
        IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_PurchaseOrderItems_Supply' AND object_id=OBJECT_ID('PurchaseOrderItems'))
            CREATE INDEX IX_PurchaseOrderItems_Supply ON PurchaseOrderItems(SupplyType, SupplyId);
    `);
}

function mapRow(r) {
    return {
        id: r.ClientId,
        dbId: r.Id,
        instrumentID: r.InstrumentId,
        quantity: r.Quantity,
        vendorId: r.VendorId,
        vendorName: r.VendorName,
        poNumber: r.PoNumber,
        orderNumber: r.OrderNumber || r.PoNumber,
        unitCost: r.UnitCost != null ? Number(r.UnitCost) : null,
        totalCost: r.TotalCost != null ? Number(r.TotalCost) : null,
        orderDate: r.OrderDate ? new Date(r.OrderDate).toISOString().slice(0, 10) : null,
        expectedDate: r.ExpectedDate ? new Date(r.ExpectedDate).toISOString().slice(0, 10) : null,
        notes: r.Notes,
        documentId: r.DocumentId,
        createdBy: r.CreatedBy,
        createdAt: r.CreatedAt,
        supplyType: r.SupplyType || null,
        supplyId: r.SupplyId != null ? r.SupplyId : null,
        status: r.Status || null,
        subtotal: r.Subtotal != null ? Number(r.Subtotal) : null,
        tax: r.Tax != null ? Number(r.Tax) : null,
        shipping: r.Shipping != null ? Number(r.Shipping) : null,
        total: r.Total != null ? Number(r.Total) : null,
        isAutoGenerated: r.IsAutoGenerated === true || r.IsAutoGenerated === 1,
        receivedDate: r.ReceivedDate || null,
        items: []
    };
}

function mapItem(r) {
    return {
        id: r.Id,
        purchaseOrderId: r.PurchaseOrderId,
        supplyType: r.SupplyType || null,
        supplyId: r.SupplyId != null ? r.SupplyId : null,
        supplyName: r.SupplyName || '',
        quantity: r.Quantity != null ? Number(r.Quantity) : null,
        unitCost: r.UnitCost != null ? Number(r.UnitCost) : null,
        lineTotal: r.LineTotal != null ? Number(r.LineTotal) : null
    };
}

async function attachItems(pool, orders) {
    if (!orders || !orders.length) return orders;
    const ids = orders.map(o => o.dbId).filter(x => x != null);
    if (!ids.length) return orders;
    const req = pool.request();
    const paramNames = ids.map((id, i) => {
        const name = 'poid' + i;
        req.input(name, sql.Int, id);
        return '@' + name;
    });
    const result = await req.query(`SELECT * FROM PurchaseOrderItems WHERE PurchaseOrderId IN (${paramNames.join(',')})`);
    const byPo = new Map();
    result.recordset.forEach(r => {
        const k = r.PurchaseOrderId;
        if (!byPo.has(k)) byPo.set(k, []);
        byPo.get(k).push(mapItem(r));
    });
    orders.forEach(o => { o.items = byPo.get(o.dbId) || []; });
    return orders;
}

async function replaceItems(pool, purchaseOrderId, items) {
    await pool.request().input('poid', sql.Int, purchaseOrderId).query('DELETE FROM PurchaseOrderItems WHERE PurchaseOrderId = @poid');
    if (!Array.isArray(items) || !items.length) return;
    for (const it of items) {
        const supplyType = toSafeString(it.supplyType, 20);
        const supplyId = it.supplyId != null && it.supplyId !== '' ? (parseInt(String(it.supplyId), 10) || null) : null;
        const supplyName = toSafeString(it.supplyName, 255);
        const quantity = it.quantity != null ? (parseInt(String(it.quantity), 10) || 0) : 0;
        const unitCost = it.unitCost != null && it.unitCost !== '' ? Number(it.unitCost) : null;
        const lineTotal = it.lineTotal != null && it.lineTotal !== ''
            ? Number(it.lineTotal)
            : (Number.isFinite(unitCost) ? unitCost * quantity : null);
        await pool.request()
            .input('poid', sql.Int, purchaseOrderId)
            .input('supplyType', sql.NVarChar(20), supplyType)
            .input('supplyId', sql.Int, supplyId)
            .input('supplyName', sql.NVarChar(255), supplyName)
            .input('quantity', sql.Int, quantity)
            .input('unitCost', sql.Decimal(18, 4), Number.isFinite(unitCost) ? unitCost : null)
            .input('lineTotal', sql.Decimal(18, 4), Number.isFinite(lineTotal) ? lineTotal : null)
            .query(`INSERT INTO PurchaseOrderItems
                (PurchaseOrderId, SupplyType, SupplyId, SupplyName, Quantity, UnitCost, LineTotal)
                VALUES (@poid, @supplyType, @supplyId, @supplyName, @quantity, @unitCost, @lineTotal)`);
    }
}

module.exports = async function (context, req) {
    const headers = {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-User-Id'
    };

    if (req.method === 'OPTIONS') {
        context.res = { status: 204, headers };
        return;
    }

    try {
        const pool = await getPool();
        await ensureTable(pool);
        const clientId = toSafeString(req.params && req.params.id, 100);
        const action = toSafeString(req.params && req.params.action, 30);

        // POST /purchase-orders/{id}/receive
        if (req.method === 'POST' && clientId && action && action.toLowerCase() === 'receive') {
            const lookup = await pool.request()
                .input('clientId', sql.NVarChar(100), clientId)
                .query('SELECT Id FROM PurchaseOrders WHERE ClientId = @clientId');
            if (!lookup.recordset.length) {
                context.res = { status: 404, headers, body: { error: 'Purchase order not found.' } };
                return;
            }
            await pool.request()
                .input('clientId', sql.NVarChar(100), clientId)
                .input('status', sql.NVarChar(30), 'Received')
                .input('receivedDate', sql.DateTime2, new Date())
                .query(`UPDATE PurchaseOrders
                        SET Status = @status, ReceivedDate = @receivedDate, ModifiedDate = GETUTCDATE()
                        WHERE ClientId = @clientId`);
            context.res = { status: 200, headers, body: { success: true, id: clientId, status: 'Received' } };
            return;
        }

        if (req.method === 'GET') {
            const { getRequestUserId, tenantVisibleUsernamesClause, TENANT_PARAM } = require('../shared/tenant');
            const tenantUserId = getRequestUserId(req);
            if (!tenantUserId) {
                context.res = { status: 200, headers, body: clientId ? null : [] };
                return;
            }
            const tenantPoFilter = tenantVisibleUsernamesClause('CreatedBy');
            if (clientId) {
                const result = await pool.request()
                    .input('clientId', sql.NVarChar(100), clientId)
                    .input(TENANT_PARAM, sql.Int, tenantUserId)
                    .query(`SELECT * FROM PurchaseOrders WHERE ClientId = @clientId AND ${tenantPoFilter}`);
                if (!result.recordset[0]) { context.res = { status: 200, headers, body: null }; return; }
                const row = mapRow(result.recordset[0]);
                await attachItems(pool, [row]);
                context.res = { status: 200, headers, body: row };
                return;
            }
            const r = pool.request().input(TENANT_PARAM, sql.Int, tenantUserId);
            const filters = [tenantPoFilter];
            const instrumentIdRaw = req.query && req.query.instrumentId ? parseInt(req.query.instrumentId, 10) : null;
            const instrumentId = Number.isInteger(instrumentIdRaw) && instrumentIdRaw > 0 && instrumentIdRaw <= 2147483647 ? instrumentIdRaw : null;
            const supplyType = req.query && req.query.supplyType ? String(req.query.supplyType).slice(0, 20) : null;
            const supplyIdRaw = req.query && req.query.supplyId ? parseInt(req.query.supplyId, 10) : null;
            // SQL INT max is 2147483647. Client may pass JS timestamp-based IDs (e.g. 1779992810223)
            // for supplies that were never synced to the API. Treat those as "no API rows" -> empty list.
            const supplyId = Number.isInteger(supplyIdRaw) && supplyIdRaw > 0 && supplyIdRaw <= 2147483647 ? supplyIdRaw : null;
            if (instrumentId) { filters.push('InstrumentId = @instrumentId'); r.input('instrumentId', sql.Int, instrumentId); }
            if (supplyType) { filters.push('(SupplyType = @supplyType OR Id IN (SELECT PurchaseOrderId FROM PurchaseOrderItems WHERE SupplyType = @supplyType))'); r.input('supplyType', sql.NVarChar(20), supplyType); }
            if (supplyId) {
                filters.push('(SupplyId = @supplyId OR Id IN (SELECT PurchaseOrderId FROM PurchaseOrderItems WHERE SupplyId = @supplyId))');
                r.input('supplyId', sql.Int, supplyId);
            } else if (req.query && req.query.supplyId) {
                // Supply id was provided but is not a valid INT (local-only supply). Return empty list.
                context.res = { status: 200, headers, body: [] };
                return;
            }
            let q = 'SELECT * FROM PurchaseOrders';
            if (filters.length) q += ' WHERE ' + filters.join(' AND ');
            q += ' ORDER BY CreatedAt DESC, Id DESC';
            const result = await r.query(q);
            const rows = result.recordset.map(mapRow);
            await attachItems(pool, rows);
            context.res = { status: 200, headers, body: rows };
            return;
        }

        if (req.method === 'POST' || req.method === 'PUT') {
            const body = req.body || {};
            const cid = toSafeString(body.id || body.clientId, 100);
            if (!cid) { context.res = { status: 400, headers, body: { error: 'id (client id) is required.' } }; return; }
            const instrumentId = body.instrumentID != null ? (parseInt(String(body.instrumentID), 10) || null) : null;
            const quantity = body.quantity != null ? (parseInt(String(body.quantity), 10) || null) : null;
            const unitCost = body.unitCost != null && body.unitCost !== '' ? Number(body.unitCost) : null;
            const totalCost = body.totalCost != null && body.totalCost !== '' ? Number(body.totalCost) : null;
            let orderDate = null;
            if (body.orderDate) { try { orderDate = new Date(body.orderDate); if (isNaN(orderDate.getTime())) orderDate = null; } catch (_) {} }
            let expectedDate = null;
            if (body.expectedDate) { try { expectedDate = new Date(body.expectedDate); if (isNaN(expectedDate.getTime())) expectedDate = null; } catch (_) {} }
            let createdAt = null;
            if (body.createdAt) { try { createdAt = new Date(body.createdAt); if (isNaN(createdAt.getTime())) createdAt = null; } catch (_) {} }
            if (!createdAt) createdAt = new Date();

            // Supplies-era fields (all optional; instrument POs leave them null)
            const supplyType = toSafeString(body.supplyType, 20);
            const supplyId = body.supplyId != null && body.supplyId !== '' ? (parseInt(String(body.supplyId), 10) || null) : null;
            const orderNumber = toSafeString(body.orderNumber || body.poNumber, 100);
            const status = toSafeString(body.status, 30);
            const subtotal = body.subtotal != null && body.subtotal !== '' ? Number(body.subtotal) : null;
            const tax = body.tax != null && body.tax !== '' ? Number(body.tax) : null;
            const shipping = body.shipping != null && body.shipping !== '' ? Number(body.shipping) : null;
            const total = body.total != null && body.total !== '' ? Number(body.total) : null;
            const isAutoGenerated = body.isAutoGenerated === true || body.isAutoGenerated === 1;

            await pool.request()
                .input('clientId', sql.NVarChar(100), cid)
                .input('instrumentId', sql.Int, instrumentId)
                .input('quantity', sql.Int, quantity)
                .input('vendorId', sql.NVarChar(50), toSafeString(body.vendorId, 50))
                .input('vendorName', sql.NVarChar(255), toSafeString(body.vendorName, 255))
                .input('poNumber', sql.NVarChar(100), toSafeString(body.poNumber, 100))
                .input('unitCost', sql.Decimal(18, 4), Number.isFinite(unitCost) ? unitCost : null)
                .input('totalCost', sql.Decimal(18, 4), Number.isFinite(totalCost) ? totalCost : null)
                .input('orderDate', sql.Date, orderDate)
                .input('expectedDate', sql.Date, expectedDate)
                .input('notes', sql.NVarChar(sql.MAX), body.notes || null)
                .input('documentId', sql.NVarChar(255), toSafeString(body.documentId || (body.document && body.document.key), 255))
                .input('createdBy', sql.NVarChar(255), toSafeString(body.createdBy, 255))
                .input('createdAt', sql.DateTime2, createdAt)
                .input('supplyType', sql.NVarChar(20), supplyType)
                .input('supplyId', sql.Int, supplyId)
                .input('orderNumber', sql.NVarChar(100), orderNumber)
                .input('status', sql.NVarChar(30), status)
                .input('subtotal', sql.Decimal(18, 4), Number.isFinite(subtotal) ? subtotal : null)
                .input('tax', sql.Decimal(18, 4), Number.isFinite(tax) ? tax : null)
                .input('shipping', sql.Decimal(18, 4), Number.isFinite(shipping) ? shipping : null)
                .input('total', sql.Decimal(18, 4), Number.isFinite(total) ? total : null)
                .input('isAutoGenerated', sql.Bit, isAutoGenerated ? 1 : 0)
                .query(`
                    MERGE PurchaseOrders WITH (HOLDLOCK) AS target
                    USING (SELECT @clientId AS ClientId) AS source ON target.ClientId = source.ClientId
                    WHEN MATCHED THEN UPDATE SET
                        InstrumentId=@instrumentId, Quantity=@quantity, VendorId=@vendorId, VendorName=@vendorName,
                        PoNumber=@poNumber, UnitCost=@unitCost, TotalCost=@totalCost, OrderDate=@orderDate,
                        ExpectedDate=@expectedDate, Notes=@notes, DocumentId=@documentId, CreatedBy=@createdBy,
                        SupplyType=@supplyType, SupplyId=@supplyId, OrderNumber=@orderNumber, Status=@status,
                        Subtotal=@subtotal, Tax=@tax, Shipping=@shipping, Total=@total,
                        IsAutoGenerated=@isAutoGenerated, ModifiedDate=GETUTCDATE()
                    WHEN NOT MATCHED THEN INSERT
                        (ClientId, InstrumentId, Quantity, VendorId, VendorName, PoNumber, UnitCost, TotalCost,
                         OrderDate, ExpectedDate, Notes, DocumentId, CreatedBy, CreatedAt,
                         SupplyType, SupplyId, OrderNumber, Status, Subtotal, Tax, Shipping, Total, IsAutoGenerated)
                        VALUES (@clientId, @instrumentId, @quantity, @vendorId, @vendorName, @poNumber, @unitCost, @totalCost,
                                @orderDate, @expectedDate, @notes, @documentId, @createdBy, @createdAt,
                                @supplyType, @supplyId, @orderNumber, @status, @subtotal, @tax, @shipping, @total, @isAutoGenerated);
                `);

            // Replace items if provided
            if (Array.isArray(body.items)) {
                const lookup = await pool.request()
                    .input('clientId', sql.NVarChar(100), cid)
                    .query('SELECT Id FROM PurchaseOrders WHERE ClientId = @clientId');
                const dbId = lookup.recordset[0] && lookup.recordset[0].Id;
                if (dbId) await replaceItems(pool, dbId, body.items);
            }

            context.res = { status: 200, headers, body: { success: true, id: cid } };
            return;
        }

        if (req.method === 'DELETE' && clientId) {
            const lookup = await pool.request()
                .input('clientId', sql.NVarChar(100), clientId)
                .query('SELECT Id FROM PurchaseOrders WHERE ClientId = @clientId');
            const dbId = lookup.recordset[0] && lookup.recordset[0].Id;
            if (dbId) {
                await pool.request().input('poid', sql.Int, dbId).query('DELETE FROM PurchaseOrderItems WHERE PurchaseOrderId = @poid');
            }
            await pool.request()
                .input('clientId', sql.NVarChar(100), clientId)
                .query('DELETE FROM PurchaseOrders WHERE ClientId = @clientId');
            context.res = { status: 200, headers, body: { success: true } };
            return;
        }

        context.res = { status: 405, headers, body: { error: 'Method not allowed.' } };
    } catch (error) {
        if (context.log) context.log.error('Purchase Orders API error:', error);
        context.res = { status: 500, headers, body: { error: error.message || 'Server error' } };
    }
};
