const { execute } = require('../shared/database');
const { successResponse, errorResponse, handleOptions } = require('../shared/response');

function toNullableInt(value) {
    if (value === null || value === undefined || value === '') return null;
    const parsed = Number.parseInt(String(value), 10);
    return Number.isInteger(parsed) ? parsed : null;
}

function toNullableDecimal(value) {
    if (value === null || value === undefined || value === '') return null;
    const parsed = Number.parseFloat(String(value));
    return Number.isFinite(parsed) ? parsed : null;
}

function toSafeString(value, maxLen = 400) {
    if (value === null || value === undefined) return null;
    const s = String(value).trim();
    if (!s) return null;
    return s.slice(0, maxLen);
}

function toDateOnlyOrNull(value) {
    if (value === null || value === undefined || value === '') return null;
    const raw = String(value).trim();
    if (!raw) return null;
    if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;

    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) return null;
    const year = parsed.getUTCFullYear();
    const month = String(parsed.getUTCMonth() + 1).padStart(2, '0');
    const day = String(parsed.getUTCDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function normalizeTicket(row) {
    return {
        id: row.Id,
        equipmentId: row.EquipmentId,
        serviceType: row.ServiceType,
        priority: row.Priority,
        status: row.Status,
        scheduledDate: row.ScheduledDate,
        completedDate: row.CompletedDate,
        vendor: row.Vendor,
        cost: row.Cost,
        description: row.Description,
        notes: row.Notes,
        isAutoGenerated: row.IsAutoGenerated === true || row.IsAutoGenerated === 1,
        createdAt: row.CreatedAt,
        updatedAt: row.UpdatedAt
    };
}

function buildPayload(body = {}) {
    return {
        equipmentId: toNullableInt(body.equipmentId || body.EquipmentId),
        serviceType: toSafeString(body.serviceType || body.ServiceType || body.type, 30) || 'Preventive',
        priority: toSafeString(body.priority || body.Priority, 20) || 'Medium',
        status: toSafeString(body.status || body.Status, 20) || 'Open',
        scheduledDate: toDateOnlyOrNull(body.scheduledDate || body.ScheduledDate),
        completedDate: toDateOnlyOrNull(body.completedDate || body.CompletedDate),
        vendor: toSafeString(body.vendor || body.Vendor, 120),
        cost: toNullableDecimal(body.cost || body.Cost) || 0,
        description: toSafeString(body.description || body.Description, 500),
        notes: toSafeString(body.notes || body.Notes, 4000),
        isAutoGenerated: !!(body.isAutoGenerated || body.IsAutoGenerated)
    };
}

module.exports = async function (context, req) {
    if (req.method === 'OPTIONS') {
        context.res = handleOptions();
        return;
    }

    try {
        const routeIdRaw = req.params.id ? String(req.params.id).trim() : '';

        if (req.method === 'GET') {
            const equipmentId = toNullableInt(req.query.equipmentId || req.query.EquipmentId);

            if (routeIdRaw) {
                const result = await execute(
                    `SELECT *
                     FROM EquipmentServiceTickets
                     WHERE Id = @id`,
                    { id: routeIdRaw }
                );

                const row = (result.recordset || [])[0] || null;
                context.res = successResponse(row ? normalizeTicket(row) : null);
                return;
            }

            const hasEquipmentFilter = Number.isInteger(equipmentId) && equipmentId > 0;
            const result = await execute(
                `SELECT *
                 FROM EquipmentServiceTickets
                 WHERE (@equipmentId IS NULL OR EquipmentId = @equipmentId)
                 ORDER BY CreatedAt DESC`,
                { equipmentId: hasEquipmentFilter ? equipmentId : null }
            );

            context.res = successResponse((result.recordset || []).map(normalizeTicket));
            return;
        }

        if (req.method === 'POST') {
            const payload = buildPayload(req.body || {});
            if (!payload.equipmentId) {
                context.res = errorResponse('equipmentId is required.', 400);
                return;
            }

            const result = await execute(
                `INSERT INTO EquipmentServiceTickets (
                    EquipmentId, ServiceType, Priority, Status,
                    ScheduledDate, CompletedDate, Vendor, Cost,
                    Description, Notes, IsAutoGenerated,
                    CreatedAt, UpdatedAt
                 )
                 OUTPUT INSERTED.Id
                 VALUES (
                    @equipmentId, @serviceType, @priority, @status,
                    @scheduledDate, @completedDate, @vendor, @cost,
                    @description, @notes, @isAutoGenerated,
                    SYSUTCDATETIME(), SYSUTCDATETIME()
                 )`,
                payload
            );

            const createdId = (result.recordset || [])[0]?.Id || null;
            context.res = successResponse({ id: createdId }, 201);
            return;
        }

        if (req.method === 'PUT') {
            if (!routeIdRaw) {
                context.res = errorResponse('Ticket id is required for update.', 400);
                return;
            }

            const payload = buildPayload(req.body || {});
            await execute(
                `UPDATE EquipmentServiceTickets
                 SET EquipmentId = COALESCE(@equipmentId, EquipmentId),
                     ServiceType = COALESCE(@serviceType, ServiceType),
                     Priority = COALESCE(@priority, Priority),
                     Status = COALESCE(@status, Status),
                     ScheduledDate = @scheduledDate,
                     CompletedDate = @completedDate,
                     Vendor = @vendor,
                     Cost = COALESCE(@cost, Cost),
                     Description = @description,
                     Notes = @notes,
                     IsAutoGenerated = COALESCE(@isAutoGenerated, IsAutoGenerated),
                     UpdatedAt = SYSUTCDATETIME()
                 WHERE Id = @id`,
                {
                    ...payload,
                    id: routeIdRaw
                }
            );

            context.res = successResponse({ success: true });
            return;
        }

        if (req.method === 'DELETE') {
            if (!routeIdRaw) {
                context.res = errorResponse('Ticket id is required for delete.', 400);
                return;
            }

            await execute(
                `DELETE FROM EquipmentServiceTickets WHERE Id = @id`,
                { id: routeIdRaw }
            );

            context.res = successResponse({ success: true });
            return;
        }

        context.res = errorResponse('Method not allowed.', 405);
    } catch (error) {
        context.log.error('equipment-services error', error);
        context.res = errorResponse('Failed to process equipment-services request.', 500, error.message);
    }
};
