const { execute } = require('../shared/database');
const { successResponse, errorResponse, handleOptions } = require('../shared/response');
const { getRequestUserId, tenantClinicScopeSql, TENANT_PARAM } = require('../shared/tenant');

function toNullableInt(value) {
    if (value === null || value === undefined || value === '') return null;
    const parsed = Number.parseInt(String(value), 10);
    return Number.isInteger(parsed) ? parsed : null;
}

function toNullableDecimal(value) {
    if (value === null || value === undefined || value === '') return null;
    const parsed = Number.parseFloat(String(value));
    return Number.isFinite(parsed) ? parsed : null;
}

function toSafeString(value, maxLen = 400) {
    if (value === null || value === undefined) return null;
    const s = String(value).trim();
    if (!s) return null;
    return s.slice(0, maxLen);
}

function getBodyValue(body, ...keys) {
    for (const key of keys) {
        if (Object.prototype.hasOwnProperty.call(body, key)) return body[key];
    }
    return undefined;
}

function hasBodyValue(body, ...keys) {
    return keys.some((key) => Object.prototype.hasOwnProperty.call(body, key));
}

function toDateOnlyOrNull(value) {
    if (value === null || value === undefined || value === '') return null;
    const raw = String(value).trim();
    if (!raw) return null;
    if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;

    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) return null;
    const year = parsed.getUTCFullYear();
    const month = String(parsed.getUTCMonth() + 1).padStart(2, '0');
    const day = String(parsed.getUTCDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function normalizeTicket(row) {
    return {
        id: row.Id,
        equipmentId: row.EquipmentId,
        title: row.Title || null,
        serviceType: row.ServiceType,
        priority: row.Priority,
        status: row.Status,
        scheduledDate: row.ScheduledDate,
        scheduledTime: row.ScheduledTime || null,
        dashboardScope: row.DashboardScope || null,
        dashboardScheduledBy: row.DashboardScheduledBy || null,
        dashboardScheduledByName: row.DashboardScheduledByName || null,
        completedDate: row.CompletedDate,
        vendor: row.Vendor,
        cost: row.Cost,
        description: row.Description,
        notes: row.Notes,
        isAutoGenerated: row.IsAutoGenerated === true || row.IsAutoGenerated === 1,
        createdAt: row.CreatedAt,
        updatedAt: row.UpdatedAt
    };
}

function buildPayload(body = {}) {
    const rawNotes = body.notes ?? body.Notes;
    const scheduledDateValue = getBodyValue(body, 'scheduledDate', 'ScheduledDate', 'scheduleDate', 'ScheduleDate');
    const scheduledTimeValue = getBodyValue(body, 'scheduledTime', 'ScheduledTime', 'scheduleTime', 'ScheduleTime', 'eventTime', 'EventTime');
    const dashboardScopeValue = getBodyValue(body, 'dashboardScope', 'DashboardScope');
    const dashboardScheduledByValue = getBodyValue(body, 'dashboardScheduledBy', 'DashboardScheduledBy');
    const dashboardScheduledByNameValue = getBodyValue(body, 'dashboardScheduledByName', 'DashboardScheduledByName');
    return {
        equipmentId: toNullableInt(body.equipmentId || body.EquipmentId),
        title: toSafeString(body.title || body.Title, 200),
        serviceType: toSafeString(body.serviceType || body.ServiceType || body.type, 30) || 'Preventive',
        priority: toSafeString(body.priority || body.Priority, 20) || 'Medium',
        status: toSafeString(body.status || body.Status, 20) || 'Open',
        scheduledDate: toDateOnlyOrNull(scheduledDateValue),
        scheduledTime: toSafeString(scheduledTimeValue, 20),
        dashboardScope: toSafeString(dashboardScopeValue, 20),
        dashboardScheduledBy: toSafeString(dashboardScheduledByValue, 100),
        dashboardScheduledByName: toSafeString(dashboardScheduledByNameValue, 200),
        hasScheduledDate: hasBodyValue(body, 'scheduledDate', 'ScheduledDate', 'scheduleDate', 'ScheduleDate') ? 1 : 0,
        hasScheduledTime: hasBodyValue(body, 'scheduledTime', 'ScheduledTime', 'scheduleTime', 'ScheduleTime', 'eventTime', 'EventTime') ? 1 : 0,
        hasDashboardScope: hasBodyValue(body, 'dashboardScope', 'DashboardScope') ? 1 : 0,
        hasDashboardScheduledBy: hasBodyValue(body, 'dashboardScheduledBy', 'DashboardScheduledBy') ? 1 : 0,
        hasDashboardScheduledByName: hasBodyValue(body, 'dashboardScheduledByName', 'DashboardScheduledByName') ? 1 : 0,
        completedDate: toDateOnlyOrNull(body.completedDate || body.CompletedDate),
        vendor: toSafeString(body.vendor || body.Vendor, 120),
        cost: toNullableDecimal(body.cost || body.Cost) || 0,
        description: toSafeString(body.description || body.Description, 500),
        notes: (rawNotes != null && String(rawNotes).trim()) ? String(rawNotes).trim() : null,
        isAutoGenerated: !!(body.isAutoGenerated || body.IsAutoGenerated)
    };
}

let dashboardScheduleColumnsEnsured = false;

async function ensureDashboardScheduleColumns() {
    if (dashboardScheduleColumnsEnsured) return;
    await execute(`
        IF OBJECT_ID('dbo.EquipmentServiceTickets', 'U') IS NOT NULL AND COL_LENGTH('dbo.EquipmentServiceTickets', 'ScheduledTime') IS NULL ALTER TABLE dbo.EquipmentServiceTickets ADD ScheduledTime NVARCHAR(20) NULL;
        IF OBJECT_ID('dbo.EquipmentServiceTickets', 'U') IS NOT NULL AND COL_LENGTH('dbo.EquipmentServiceTickets', 'DashboardScope') IS NULL ALTER TABLE dbo.EquipmentServiceTickets ADD DashboardScope NVARCHAR(20) NULL;
        IF OBJECT_ID('dbo.EquipmentServiceTickets', 'U') IS NOT NULL AND COL_LENGTH('dbo.EquipmentServiceTickets', 'DashboardScheduledBy') IS NULL ALTER TABLE dbo.EquipmentServiceTickets ADD DashboardScheduledBy NVARCHAR(100) NULL;
        IF OBJECT_ID('dbo.EquipmentServiceTickets', 'U') IS NOT NULL AND COL_LENGTH('dbo.EquipmentServiceTickets', 'DashboardScheduledByName') IS NULL ALTER TABLE dbo.EquipmentServiceTickets ADD DashboardScheduledByName NVARCHAR(200) NULL;
    `);
    dashboardScheduleColumnsEnsured = true;
}

module.exports = async function (context, req) {
    if (req.method === 'OPTIONS') {
        context.res = handleOptions();
        return;
    }

    try {
        const routeIdRaw = req.params.id ? String(req.params.id).trim() : '';
        await ensureDashboardScheduleColumns();

        if (req.method === 'GET') {
            const equipmentId = toNullableInt(req.query.equipmentId || req.query.EquipmentId);
            const tenantUserId = getRequestUserId(req);
            if (!tenantUserId) {
                context.res = successResponse(routeIdRaw ? null : []);
                return;
            }

            if (routeIdRaw) {
                const result = await execute(
                    `SELECT t.*
                     FROM EquipmentServiceTickets t
                     INNER JOIN Equipment e ON e.Id = t.EquipmentId
                     WHERE t.Id = @id AND ${tenantClinicScopeSql('e.ClinicId')}`,
                    { id: routeIdRaw, [TENANT_PARAM]: tenantUserId }
                );

                const row = (result.recordset || [])[0] || null;
                context.res = successResponse(row ? normalizeTicket(row) : null);
                return;
            }

            const hasEquipmentFilter = Number.isInteger(equipmentId) && equipmentId > 0;
            const result = await execute(
                `SELECT t.*
                 FROM EquipmentServiceTickets t
                 INNER JOIN Equipment e ON e.Id = t.EquipmentId
                 WHERE (@equipmentId IS NULL OR t.EquipmentId = @equipmentId)
                   AND ${tenantClinicScopeSql('e.ClinicId')}
                 ORDER BY t.CreatedAt DESC`,
                { equipmentId: hasEquipmentFilter ? equipmentId : null, [TENANT_PARAM]: tenantUserId }
            );

            context.res = successResponse((result.recordset || []).map(normalizeTicket));
            return;
        }

        if (req.method === 'POST') {
            const payload = buildPayload(req.body || {});
            if (!payload.equipmentId) {
                context.res = errorResponse('equipmentId is required.', 400);
                return;
            }

            const result = await execute(
                `INSERT INTO EquipmentServiceTickets (
                    EquipmentId, Title, ServiceType, Priority, Status,
                  ScheduledDate, ScheduledTime, DashboardScope, DashboardScheduledBy, DashboardScheduledByName,
                  CompletedDate, Vendor, Cost,
                    Description, Notes, IsAutoGenerated,
                    CreatedAt, UpdatedAt
                 )
                 OUTPUT INSERTED.Id
                 VALUES (
                    @equipmentId, @title, @serviceType, @priority, @status,
                  @scheduledDate, @scheduledTime, @dashboardScope, @dashboardScheduledBy, @dashboardScheduledByName,
                  @completedDate, @vendor, @cost,
                    @description, @notes, @isAutoGenerated,
                    SYSUTCDATETIME(), SYSUTCDATETIME()
                 )`,
                payload
            );

            const createdId = (result.recordset || [])[0]?.Id || null;
            context.res = successResponse({ id: createdId }, 201);
            return;
        }

        if (req.method === 'PUT') {
            if (!routeIdRaw) {
                context.res = errorResponse('Ticket id is required for update.', 400);
                return;
            }

            const payload = buildPayload(req.body || {});
            await execute(
                `UPDATE EquipmentServiceTickets
                 SET EquipmentId = COALESCE(@equipmentId, EquipmentId),
                     Title = @title,
                     ServiceType = COALESCE(@serviceType, ServiceType),
                     Priority = COALESCE(@priority, Priority),
                     Status = COALESCE(@status, Status),
                     ScheduledDate = CASE WHEN @hasScheduledDate = 1 THEN @scheduledDate ELSE ScheduledDate END,
                     ScheduledTime = CASE WHEN @hasScheduledTime = 1 THEN @scheduledTime ELSE ScheduledTime END,
                     DashboardScope = CASE WHEN @hasDashboardScope = 1 THEN @dashboardScope ELSE DashboardScope END,
                     DashboardScheduledBy = CASE WHEN @hasDashboardScheduledBy = 1 THEN @dashboardScheduledBy ELSE DashboardScheduledBy END,
                     DashboardScheduledByName = CASE WHEN @hasDashboardScheduledByName = 1 THEN @dashboardScheduledByName ELSE DashboardScheduledByName END,
                     CompletedDate = @completedDate,
                     Vendor = @vendor,
                     Cost = COALESCE(@cost, Cost),
                     Description = @description,
                     Notes = @notes,
                     IsAutoGenerated = COALESCE(@isAutoGenerated, IsAutoGenerated),
                     UpdatedAt = SYSUTCDATETIME()
                 WHERE Id = @id`,
                {
                    ...payload,
                    id: routeIdRaw
                }
            );

            context.res = successResponse({ success: true });
            return;
        }

        if (req.method === 'DELETE') {
            if (!routeIdRaw) {
                context.res = errorResponse('Ticket id is required for delete.', 400);
                return;
            }

            await execute(
                `DELETE FROM EquipmentServiceTickets WHERE Id = @id`,
                { id: routeIdRaw }
            );

            context.res = successResponse({ success: true });
            return;
        }

        context.res = errorResponse('Method not allowed.', 405);
    } catch (error) {
        context.log.error('equipment-services error', error);
        context.res = errorResponse('Failed to process equipment-services request.', 500, error.message);
    }
};
